BeachsideSeafood.UI/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeachsideSeafood.Data;

namespace BeachsideSeafood.UI.Controllers
{
    public class LocationsController : Controller
    {
        //private BeachsideSeafoodEntities db = new BeachsideSeafoodEntities();
        unitofwork uow = new unitofwork();

        // GET: Locations
        public ActionResult Index()
        {
            return View(uow.LocationRepository.Get());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = uow.LocationRepository.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationID,StoreNumber,City,State")] Location location)
        {
            if (ModelState.IsValid)
            {
                uow.LocationRepository.Add(location);
                uow.Save();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = uow.LocationRepository.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationID,StoreNumber,City,State")] Location location)
        {
            if (ModelState.IsValid)
            {
                uow.LocationRepository.Update(location);
               uow.Save();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = uow.LocationRepository.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = uow.LocationRepository.Find(id);
           uow.LocationRepository.Remove(location);
           uow.Save();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

BeachsideSeafood.UI/Controllers/OpenPositionIDsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeachsideSeafood.Data;

namespace BeachsideSeafood.UI.Controllers
{
    public class OpenPositionIDsController : Controller
    {
        //private BeachsideSeafoodEntities db = new BeachsideSeafoodEntities();
        unitofwork uow = new unitofwork();

        // GET: OpenPositionIDs
        public ActionResult Index()
        {
            var openPositionIDs = uow.OpenPositionIDRepository.Get();
            return View(openPositionIDs.ToList());
        }

        // GET: OpenPositionIDs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPositionID openPositionID = uow.OpenPositionIDRepository.Find(id);
            if (openPositionID == null)
            {
                return HttpNotFound();
            }
            return View(openPositionID);
        }

        // GET: OpenPositionIDs/Create
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(uow.LocationRepository.Get(), "LocationID", "StoreNumber");
            ViewBag.PositionID = new SelectList(uow.PositionRepository.Get(), "PositionID", "Title");
            return View();
        }

        // POST: OpenPositionIDs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OpenPositionID1,PositionID,LocationID")] OpenPositionID openPositionID)
        {
            if (ModelState.IsValid)
            {
                uow.OpenPositionIDRepository.Add(openPositionID);
                uow.Save();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(uow.LocationRepository.Get(), "LocationID", "StoreNumber", openPositionID.LocationID);
            ViewBag.PositionID = new SelectList(uow.PositionRepository.Get(), "PositionID", "Title", openPositionID.PositionID);
            return View(openPositionID);
        }

        // GET: OpenPositionIDs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPositionID openPositionID = uow.OpenPositionIDRepository.Find(id);
            if (openPositionID == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(uow.LocationRepository.Get(), "LocationID", "StoreNumber", openPositionID.LocationID);
            ViewBag.PositionID = new SelectList(uow.PositionRepository.Get(), "PositionID", "Title", openPositionID.PositionID);
            return View(openPositionID);
        }

        // POST: OpenPositionIDs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OpenPositionID1,PositionID,LocationID")] OpenPositionID openPositionID)
        {
            if (ModelState.IsValid)
            {
                uow.OpenPositionIDRepository.Update(openPositionID);
                uow.Save();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(uow.LocationRepository.Get(), "LocationID", "StoreNumber", openPositionID.LocationID);
            ViewBag.PositionID = new SelectList(uow.PositionRepository.Get(), "PositionID", "Title", openPositionID.PositionID);
            return View(openPositionID);
        }

        // GET: OpenPositionIDs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPositionID openPositionID = uow.OpenPositionIDRepository.Find(id);
            if (openPositionID == null)
            {
                return HttpNotFound();
            }
            return View(openPositionID);
        }

        // POST: OpenPositionIDs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPositionID openPositionID = uow.OpenPositionIDRepository.Find(id);
            uow.OpenPositionIDRepository.Remove(openPositionID);
            uow.Save();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

BeachsideSeafood.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top"> 
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Beachside Seafood", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                More Options
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Open Positions", "Index", "OpenPositionIDs")</li>
                                <li>@Html.ActionLink("Applications", "Index", "Applications")</li>
                                @if ((Request.IsAuthenticated && User.IsInRole("Admin")) || (Request.IsAuthenticated && User.IsInRole("Manager")))
                                {
                                    <li>@Html.ActionLink("Positions", "Index", "Positions")</li>
                                    <li>@Html.ActionLink("Store Locations", "Index", "Locations")</li>
                                }
                            </ul>
                        </div>
                    </li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Beachside Seafood</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript">
        $(function () {
            $('#navbar li').each(function () {
                if ($(this).find('a').attr('href') == window.location.pathname) {
                    $(this).addClass('current');
                }
            })
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>