BeachsideSeafood.UI/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeachsideSeafood.Data;
using BeachsideSeafood.Data.Exceptions;
using Microsoft.AspNet.Identity;

namespace BeachsideSeafood.UI.Controllers
{
    public class ApplicationsController : Controller
    {
        //private BeachsideSeafoodEntities db = new BeachsideSeafoodEntities();
        unitofwork uow = new unitofwork();


        // GET: Applications
        public ActionResult Index()
        {
            //var applications = uow.Applications.Include(a => a.OpenPositionID1);
            if (User.IsInRole("Manager") || User.IsInRole("Admin"))
            {
                return View(uow.ApplicationRepository.Get("OpenPositionID1"));

            }
            else
            {
                var application = uow.ApplicationRepository.Get().Where(x => x.UserID == User.Identity.GetUserId());

                return View(application);
            }

            }
        

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = uow.ApplicationRepository.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create(int? id)
        {

            if (id.HasValue)
                ViewBag.OpenPositionID = id;
            //    ViewBag.OpenPositionID = id.Value;
                
            //ViewBag.OpenPositionID = new SelectList(uow.OpenPositionIDRepository.Get(), "OpenPositionID1", "OpenPositionID1",id);


            ViewBag.UserID = new SelectList(uow.UserRepository.Get(), "Id", "Id", User.Identity.GetUserId()); //TO DO fix this to transfer aspnet user id to user id for application
            return View();
        }



        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,IsDeclined,ResumeFilename")] Application application, HttpPostedFileBase resumeFilename)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                //default the value of the image name to our no phote name
                //noimage.jpg
                string resumeName = "";

                //see if the user uploaded an image
                if (resumeFilename != null)
                {
                    //get filename
                    resumeName = resumeFilename.FileName;

                    //use the filename to get the extension
                    string ext = resumeName.Substring(resumeName.LastIndexOf('.'));

                    //create a list of VALID extensions
                    //checking to make sure that malicious code is not uploaded
                    //to our application
                    string[] goodExts = new string[]
                        {".docx",".doc",".pdf",".rtf",".html",".odf",".txt" };

                    //if the extension is not contained in that list
                    if (!goodExts.Contains(ext))
                    {
                        ////rename it back to noImage.jpg
                        //imageName = "noimage.jpg";//default imagename

                        //lets throw the flag on this play - cause exception that explains problem
                        //log.Info(User.Identity.Name + " tried to upload a bad file of type" + ext);
                        throw new InvalidFileTypeException("invalid file type uploaded. only image filetypes are allowed.");
                    }//end if
                     //else
                    else
                    {
                        //rename the image GUID - Global Unique IDentifier
                        resumeName = Guid.NewGuid() + ext;

                        //save the file to the webserver
                        resumeFilename.SaveAs(Server.
                            MapPath("~/Content/Resumes/" + resumeName));

                        ////using our service
                        string savePath = Server.MapPath("~/Content/Resumes/");
                        ////convert the file from httppostedfilebbase to image
                        //Image convertedImage = Image.FromStream(bookImage.InputStream);
                        ////set the max size for the full size images in px
                        //int maxImageSize = 500;

                        ////set the max size for thumbs
                        //int maxThumbSize = 100;

                        ////call the image service to resize and sve the image
                        //ImageServices.ResizeImage(savePath, imageName, convertedImage, maxImageSize, maxThumbSize);

                    }//end else
                }
                //no matter what save the filename to the database
                application.ResumeFilename = resumeName;

                #endregion
                //application.UserID = application.AspNetUser.UserName;
                application.ApplicationDate = DateTime.Now;
                application.UserID = User.Identity.GetUserId();
                uow.ApplicationRepository.Add(application);
                uow.Save();
                return RedirectToAction("Index");
            }

            ViewBag.OpenPositionID = new SelectList(uow.OpenPositionIDRepository.Get(), "OpenPositionID1", "OpenPositionID1", application.OpenPositionID);
            return View(application);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Application application = uow.ApplicationRepository.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.OpenPositionID = new SelectList(uow.OpenPositionIDRepository.Get(), "OpenPositionID1", "OpenPositionID1", application.OpenPositionID);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,IsDeclined,ResumeFilename")] Application application)
        {
            if (ModelState.IsValid)
            {
                uow.ApplicationRepository.Update(application);
                uow.Save();
                return RedirectToAction("Index");
            }
            ViewBag.OpenPositionID = new SelectList(uow.OpenPositionIDRepository.Get(), "OpenPositionID1", "OpenPositionID1", application.OpenPositionID);
            return View(application);
        }

	
        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = uow.ApplicationRepository.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = uow.ApplicationRepository.Find(id);
            uow.ApplicationRepository.Remove(application);
            uow.Save();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

BeachsideSeafood.UI/Views/Applications/Create.cshtml
@model BeachsideSeafood.Data.Application
@using BeachsideSeafood.Data;

@{
    ViewBag.Title = "Apply";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "Applications", FormMethod.Post, new { @enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <input type="hidden" name="ApplicationDate" value="01/01/2017" />
    <div class="form-horizontal">
        <h4>Application</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.OpenPositionID, "OpenPositionID", htmlAttributes: new {  @class = "control-label col-md-2" })*@
            <div class="col-md-10">

                @*@Html.DropDownList("OpenPositionID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.OpenPositionID, "", new { @class = "text-danger" })
                @Html.Hidden("OpenPositionID", (int)ViewBag.OpenPositionID)

                @*<input type="hidden" name="OpenPositionID" value="@ViewBag.OpenPositionID" />   this will be needed later when the apply button on open positions works *@
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.HiddenFor(model => model.ApplicationDate, htmlAttributes: new { @value = "01/01/2017", @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
            </div>
        </div>*@
@if (User.IsInRole("Admin") || User.IsInRole("Manager"))
{
        <div class="form-group">
            @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
            </div>
        </div>
}
        @*<div class="form-group">
            @Html.LabelFor(model => model.IsDeclined, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeclined)
                    @Html.ValidationMessageFor(model => model.IsDeclined, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ResumeFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ResumeFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResumeFilename, "", new { @class = "text-danger" })*@
                <input type="file" name="ResumeFilename" />

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeachsideSeafood.UI/Views/Applications/Delete.cshtml
@model BeachsideSeafood.Data.Application

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeclined)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeclined)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResumeFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResumeFilename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenPositionID1.OpenPositionID1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenPositionID1.OpenPositionID1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BeachsideSeafood.UI/Views/Applications/Details.cshtml
@model BeachsideSeafood.Data.Application

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManagerNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeclined)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeclined)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResumeFilename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResumeFilename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenPositionID1.OpenPositionID1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenPositionID1.OpenPositionID1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ApplicationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BeachsideSeafood.UI/Views/Applications/Edit.cshtml
@model BeachsideSeafood.Data.Application

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Application</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationID)

        <div class="form-group">
            @Html.LabelFor(model => model.OpenPositionID, "OpenPositionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OpenPositionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OpenPositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeclined, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeclined)
                    @Html.ValidationMessageFor(model => model.IsDeclined, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResumeFilename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResumeFilename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResumeFilename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeachsideSeafood.UI/Views/Applications/Index.cshtml
@model IEnumerable<BeachsideSeafood.Data.Application>

@{
    ViewBag.Title = "Applications";
}

<h2>@ViewBag.Title</h2>
@if (User.IsInRole("Manager") || User.IsInRole("Admin"))
{
<p>
    @Html.ActionLink("Create New", "Create")
</p>}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManagerNotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeclined)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResumeFilename)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpenPositionID1.Position.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManagerNotes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeclined)
        </td>
        <td>  
            @* fix this *@
            @*@Html.DisplayFor(modelItem => item.ResumeFilename)*@
            <a href="~/Content/Resumes/@item.ResumeFilename">@item.ResumeFilename</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpenPositionID1.Position.Title)
        </td>
        <td>
            
            
            @Html.ActionLink("Details", "Details", new { id = item.ApplicationID })
@if (User.IsInRole("Manager") || User.IsInRole("Admin"))
{

            @Html.ActionLink("Edit", "Edit", new { id=item.ApplicationID }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.ApplicationID })
            }
        </td>
    </tr>
}

</table>